package com.ticdiaspora.domain.model.enums;

public enum AuditAction {
    MEMBER_CREATED,
    MEMBER_UPDATED,
    MEMBER_SUSPENDED,
    MEMBER_REACTIVATED,
    CONTRIBUTION_VALIDATED,
    PENALTY_CANCELLED,
    PENALTY_WAIVED,
    ABSENCE_EXCEPTIONALLY_APPROVED,
    CHAIRPERSON_CHANGED,
    MEETING_AUTO_COMPLETED,
    MEETING_MINUTES_UPDATED,
    TONTINE_CYCLE_CLOSED,
    CHARITY_OUTCOME_CREATED
}
