package com.ticdiaspora.domain.model.enums;

public enum NotificationType {
    MEETING_REMINDER,
    CHAIRPERSON_ASSIGNED,
    CONTRIBUTION_REMINDER,
    CONTRIBUTION_VALIDATED,
    PENALTY_CREATED,
    ABSENCE_REQUEST_SUBMITTED,
    ABSENCE_APPROVED,
    ABSENCE_REJECTED,
    ABSENCE_THRESHOLD_WARNING,
    BENEFICIARY_CONFIRMATION_REQUIRED,
    CYCLE_CLOSED
}
